# Generated by Django 6.0.1 on 2026-04-20 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_genre_movie_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=10)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.seat')),
            ],
        ),
    ]
