# Generated by Django 6.0.1 on 2026-05-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_booking_booked_at_alter_booking_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
